### ISSUE TITLE
程序无法中断运行

### ISSUE THREAD

**Issue by futurepaycc** [nicai0609/Python-CTPAPI#4]
md_demo.py在终端下ctrl+c没有反映，
手工加上try/except keyboardinterrupt/exit() 也是如止

arch linux/python 3.7.7

**Comment by lin-ww** [comment]
ps kill 杀死进程吧

**Comment by lin-ww** [comment]
> md_demo.py在终端下ctrl+c没有反映，
> 手工加上try/except keyboardinterrupt/exit() 也是如止
> 
> arch linux/python 3.7.7

ps kill杀死进程吧

**Comment by nicai0609** [comment]
是因为末尾调用了join函数的作用，join是阻塞主线程的，swig转换可能屏蔽了SIGINT信号，所以ctrl+c没有反应。
可以用time.sleep替换join函数解决。
